name: Package

description: packaging

runs:
  using: composite
  steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-node@v3
      with:
        node-version-file: .node-version
        cache: "npm"

    - name: install apt packages
      shell: bash
      run: |
        sudo apt update
        sudo apt install -y wine convmv

    - shell: bash
      run: npm ci

    - shell: bash
      run: npm run package
